services:
  - type: web
    name: prohire-backend
    runtime: node
    repo: https://github.com/clivetafa/prohire-backend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRE
        value: 15m
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://prohire.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
